// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Only load dotenv if DATABASE_URL is not already set
if (!process.env.DATABASE_URL) {
  try {
    require("dotenv").config();
  } catch (e) {
    // dotenv might not be available during certain build steps
  }
}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "postgresql://user:password@localhost:5432/possenafal",
  },
});
